import = ["~/.config/alacritty/catppuccin-mocha.toml"]

shell = "zsh"

[window]

padding = {x = 12, y = 12}
dynamic_padding = true
opacity = 0.9
blur = true

[font]
normal = {family = "JetBrainsMonoNerdFont"}
size = 13
offset = {x = 0, y = 0}


